### PR TITLE
Very small typo fix - advise/advice 

### PR DESCRIPTION
**Pull request by larsnaesbye**
Fixes https://github.com/gravitee-io/issues/issues/4379

### CODE REVIEW

**Comment by aelamrani** [comment]
Hi @larsnaesbye,

Thanks for the contribution.

May I ask you to create an issue first and attach the PR to this issue?

See https://github.com/gravitee-io/gravitee-portal-webui/blob/master/CONTRIBUTING.adoc

**Comment by larsnaesbye** [comment]
I did create the issue, but after the PR was made.

**Comment by larsnaesbye** [comment]
https://github.com/gravitee-io/issues/issues/4379

**Comment by larsnaesbye** [comment]
@aelamrani I have added it in description and comments, and it still doesn't link it here on GitHub.

**Comment by larsnaesbye** [comment]
Fixes https://github.com/gravitee-io/issues/issues/4379

**Comment by larsnaesbye** [comment]
Okay, I got it linked - I forgot it has to be mentioned in the description :D

**Comment by aelamrani** [comment]
Thanks for this @larsnaesbye 

May I ask you to squash your commits to a single one to keep a clear history?

**Comment by aelamrani** [comment]
👍

**Pull request merged**
